import { test, expect } from '@playwright/test';
test('R00012', async ({ page }) => {
    await page.goto('https://wsr.surin.rmuti.ac.th/html/QuotaWSR/index.php');
    await page.getByRole('button', { name: 'สมัครเรียน' }).click();
    await page.getByRole('link', { name: '    สมัครเรียน ปีการศึกษา' }).click();
    await page.getByPlaceholder(' กรุณากรอกเลชบัตรบัตรประชาชน / ID Card ').click();
    await page.getByPlaceholder(' กรุณากรอกเลชบัตรบัตรประชาชน / ID Card ').fill('1101801346531');
    await page.getByPlaceholder(' กรุณากรอกเลชบัตรบัตรประชาชน / ID Card ').press('Enter');
    await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
    await page.locator('input[name="sex"]').first().check();
    await page.getByPlaceholder('    เบอร์โทรศัพท์ที่สามารถติดต่อได้ 0000000000  ').click();
    await page.getByPlaceholder('    เบอร์โทรศัพท์ที่สามารถติดต่อได้ 0000000000  ').fill('123456789');
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00012/R00012-1.png'});
    await page.locator('input[name="edu"]').first().check();
    await page.getByRole('button', { name: 'ลงทะเบียน' }).click();
    await expect(page.locator('#tt13')).toBeVisible();
    await page.getByText('โปรดกรอกเบอร์โทรศัพท์ติดต่อให้ถูกต้อง').click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00012/R00012-2.png',fullPage:true });
    await expect(page.getByText('โปรดกรอกเบอร์โทรศัพท์ติดต่อให้ถูกต้อง')).toBeVisible();
});