import { test, expect } from '@playwright/test';
test('R00037', async ({ page }) => {
    await page.goto('https://payment.surin.rmuti.ac.th/');
    await page.locator('#login').click();
    await page.locator('#login').fill('1329901205307');
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00037/R00037-1.png'});
    await page.getByRole('button', { name: 'LOGIN' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00037/R00037-2.png'});
    await page.getByRole('link', { name: ' ประวัติส่วนตัว' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00037/R00037-3.png'});
    await page.locator('#member_student_id').click();
    await page.locator('#member_student_id').press('ControlOrMeta+a');
    await page.locator('#member_student_id').fill('67222310160-0');
    await page.locator('#member_name').click();
    await page.locator('#member_name').press('ControlOrMeta+a');
    await page.locator('#member_name').fill('นายกิตติธัช อิทธิผล');
    await page.getByRole('button', { name: '...' }).click();
    await page.getByLabel('ระดับ').selectOption('d40');
    await page.getByLabel('คณะ', { exact: true }).selectOption('d3');
    await page.getByLabel('สาขา', { exact: true }).selectOption('d46');
    await page.getByLabel('โปรแกรมวิชา').selectOption('d91');
    await page.getByRole('button', { name: 'เลือก' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00037/R00037-4.png'});
    await page.getByRole('button', { name: 'ปรับปรุงข้อมูล' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00037/R00037-5.png'});
});