import { test, expect } from '@playwright/test';
test('R00035', async ({ page }) => {
    await page.goto('https://payment.surin.rmuti.ac.th/');
    await page.locator('#login').click();
    await page.locator('#login').fill('1329901205307');
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00035/R00035-1.png'});
    await page.getByRole('button', { name: 'LOGIN' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00035/R00035-2.png'});
    await page.getByRole('link', { name: 'คลิก' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00035/R00035-3.png'});
    await page.getByRole('button', { name: 'แจ้งชำระ' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00035/R00035-4.png'});
    await page.locator('#bank_repay_id-error').waitFor({ state: 'visible' });
    await expect(page.locator('#bank_repay_id-error')).toBeVisible({ timeout: 5000 });
    await page.locator('#payment_date-error').waitFor({ state: 'visible' });
    await expect(page.locator('#payment_date-error')).toBeVisible({ timeout: 5000 });
    await page.locator('#payment_time-error').waitFor({ state: 'visible' });
    await expect(page.locator('#payment_time-error')).toBeVisible({ timeout: 5000 });
    await page.locator('#payment_money-error').waitFor({ state: 'visible' });
    await expect(page.locator('#payment_money-error')).toBeVisible({ timeout: 5000 });
    await page.getByText('กรุณาไฟล์').waitFor({ state: 'visible' });
    await expect(page.getByText('กรุณาไฟล์')).toBeVisible({ timeout: 5000 });
});