import { test, expect } from '@playwright/test';
test('R00015', async ({ page }) => {
    await page.goto('https://wsr.surin.rmuti.ac.th/html/QuotaWSR/index.php');
    await page.getByRole('button', { name: 'สมัครเรียน' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00015/R00015-1.png'});
    await page.getByRole('link', { name: '    สมัครเรียน ปีการศึกษา' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00015/R00015-2.png'});
    await page.getByRole('textbox', { name: 'กรุณากรอกเลชบัตรบัตรประชาชน / ID Card' }).click();
    await page.getByRole('textbox', { name: 'กรุณากรอกเลชบัตรบัตรประชาชน / ID Card' }).fill('1329901205307');
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00015/R00015-3.png'});
    await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00015/R00015-4.png'});
    await page.locator('input[name="sex"]').first().check();
    await page.getByRole('textbox', { name: 'ขยัน' }).click();
    await page.getByRole('textbox', { name: 'ขยัน' }).fill('กิตติธัช');
    await page.getByRole('textbox', { name: 'หมั่นเรียน' }).click();
    await page.getByRole('textbox', { name: 'หมั่นเรียน' }).fill('อิทธิผล');
    await page.getByRole('textbox', { name: 'เบอร์โทรศัพท์ที่สามารถติดต่อได้' }).click();
    await page.getByRole('textbox', { name: 'เบอร์โทรศัพท์ที่สามารถติดต่อได้' }).fill('0909036683');
    await page.getByRole('textbox', { name: 'สาขาที่สำเร็จการศึกษา / กำลังศึกษา' }).click();
    await page.getByRole('textbox', { name: 'สาขาที่สำเร็จการศึกษา / กำลังศึกษา' }).fill('คอมพิวเตอร์ระบบเครือข่าย');
    await page.getByRole('textbox', { name: 'สถาบันศึกษาที่จบ / กำลังศึกษา' }).click();
    await page.getByRole('textbox', { name: 'สถาบันศึกษาที่จบ / กำลังศึกษา' }).fill('วิทยาลัยเทคนิคสุรินทร์');
    await page.locator('#ddlProvince').selectOption('สุรินทร์');
    await page.locator('input[name="edu"]').nth(2).check();
    await page.locator('#degree1').check();
    await page.locator('#program').selectOption('2230631');
    await page.waitForTimeout(5000);
    await page.screenshot({ path: 'C:/Automation-Test/automation_github/img/R00015/R00015-5.png' , fullPage: true});
    await page.getByRole('button', { name: 'ลงทะเบียน' }).click();
    await expect(page.getByText('ข้อมูลการสมัครเรียน')).toBeVisible();
    await expect(page.getByText('ชื่อ : นาย กิตติธัช อิทธิผล')).toBeVisible();
});